import type { Airport } from "@/lib/types";

export const airports = [
  {
    slug: "jfk",
    iata: "JFK",
    icao: "KJFK",
    name: "John F. Kennedy International Airport",
    shortName: "New York JFK",
    city: "New York",
    country: "United States",
    region: "North America",
    coordinates: { latitude: 40.6413, longitude: -73.7781 },
    airportistScore: 7.4,
    scoreBreakdown: {
      comfort: 7.1,
      navigation: 6.7,
      food: 7.6,
      transport: 7.9,
      disruptionResilience: 7.4,
    },
    stats: {
      annualPassengers: "62M",
      terminals: "5 active terminals",
      onTimePercentage: 73,
      averageSecurityMinutes: 22,
    },
    summary:
      "JFK can feel fragmented, but it rewards travelers who know their terminal and lean on AirTrain connections instead of guessing at curbside traffic.",
    bestFor: ["International options", "AirTrain access", "Strong lounge network"],
    watchOutFor: ["Terminal changes", "Peak-hour taxi queues", "Long immigration waves"],
    amenities: [
      {
        id: "jfk-food",
        label: "Strong terminal dining",
        category: "food",
        description: "Terminal 4 and Terminal 5 have the most reliable preflight meals.",
        quality: "good",
        isFeatured: true,
      },
      {
        id: "jfk-lounge",
        label: "Deep lounge choice",
        category: "lounge",
        description: "SkyTeam, oneworld, Priority Pass, and airline lounges vary heavily by terminal.",
        quality: "excellent",
      },
      {
        id: "jfk-wifi",
        label: "Fast free WiFi",
        category: "wifi",
        description: "Free airport WiFi is usually stable enough for calls and streaming.",
        quality: "good",
      },
      {
        id: "jfk-family",
        label: "Family services",
        category: "family",
        description: "Nursing rooms and family restrooms are available, but spacing differs by terminal.",
        quality: "good",
      },
      {
        id: "jfk-transport",
        label: "AirTrain connected",
        category: "transport",
        description: "AirTrain links terminals with Jamaica and Howard Beach rail connections.",
        quality: "excellent",
        isFeatured: true,
      },
    ],
    tips: [
      {
        id: "jfk-terminal-first",
        category: "navigation",
        title: "Treat each terminal like a separate airport",
        summary: "Check your exact terminal before leaving for JFK.",
        details:
          "Airside terminal transfers are limited, so a wrong drop-off can cost more time than the security line itself.",
        pro: "Knowing the terminal early makes AirTrain and curb choices much easier.",
        con: "Some airline apps lag during irregular operations.",
      },
      {
        id: "jfk-airtrain",
        category: "transport",
        title: "Use AirTrain during Manhattan rush hour",
        summary: "Jamaica Station plus LIRR is often calmer than a taxi queue.",
        details:
          "If you are carrying manageable luggage, the rail route can beat road traffic and avoids the worst rideshare surge windows.",
        pro: "Predictable travel time into Midtown.",
        con: "Not ideal for families with many bags.",
      },
      {
        id: "jfk-t5-power",
        category: "layover",
        title: "Terminal 5 has the easiest casual layover",
        summary: "Look upstairs and away from central concessions for quieter seats.",
        details:
          "JetBlue-heavy Terminal 5 has reliable charging and food, but central gate areas fill fast after weather delays.",
      },
      {
        id: "jfk-security-wave",
        category: "security",
        title: "Avoid the late-afternoon international wave",
        summary: "Security and check-in lines build hard before Europe departures.",
        details:
          "For long-haul evening flights, arrive earlier than the generic airline guidance if you need to check bags.",
      },
    ],
    transport: [
      {
        type: "train",
        name: "AirTrain + LIRR",
        summary: "The most reliable public route to Midtown Manhattan.",
        timeToCity: "35-45 min",
        cost: "$",
        insiderTip: "Choose Jamaica for LIRR speed; Howard Beach is better for southern Brooklyn.",
      },
      {
        type: "rideshare",
        name: "Uber or Lyft",
        summary: "Convenient, but surge pricing and pickup loops are common.",
        timeToCity: "45-90 min",
        cost: "$$$",
        insiderTip: "Compare taxi flat-rate pricing before confirming a high surge fare.",
      },
      {
        type: "parking",
        name: "Long-term parking",
        summary: "Best booked ahead during school holidays.",
        timeToCity: "On airport",
        cost: "$$",
        insiderTip: "Use AirTrain from remote lots instead of hunting for terminal garage space.",
      },
    ],
    disruption: {
      status: "moderate",
      departureDelayMinutes: 38,
      departureDelayPercent: 31,
      arrivalDelayMinutes: 29,
      arrivalDelayPercent: 24,
      cancellationsPercent: 2.1,
      alerts: ["Northeast weather", "International arrival banks"],
      lastUpdated: new Date("2026-05-31T08:40:00Z"),
    },
    reviews: [
      {
        id: "jfk-review-1",
        author: "Maya R.",
        tripType: "Solo business",
        rating: 4,
        title: "Great if you respect the terminal split",
        body: "AirTrain was painless, but I would never arrive without checking my terminal twice.",
        date: "2026-04-18",
      },
      {
        id: "jfk-review-2",
        author: "Jonas K.",
        tripType: "Family long-haul",
        rating: 3,
        title: "Good food, stressful lines",
        body: "Terminal 4 had solid food and clean seating. Bag drop was the stressful part.",
        date: "2026-03-09",
      },
    ],
    photos: [
      { id: "jfk-photo-1", alt: "Terminal concourse seating", colorClass: "from-sky-200 to-slate-500" },
      { id: "jfk-photo-2", alt: "AirTrain platform", colorClass: "from-emerald-200 to-cyan-700" },
      { id: "jfk-photo-3", alt: "International gates", colorClass: "from-zinc-200 to-blue-800" },
    ],
  },
  {
    slug: "lax",
    iata: "LAX",
    icao: "KLAX",
    name: "Los Angeles International Airport",
    shortName: "Los Angeles LAX",
    city: "Los Angeles",
    country: "United States",
    region: "North America",
    coordinates: { latitude: 33.9416, longitude: -118.4085 },
    airportistScore: 6.9,
    scoreBreakdown: {
      comfort: 6.8,
      navigation: 6.4,
      food: 7.7,
      transport: 5.9,
      disruptionResilience: 6.8,
    },
    stats: {
      annualPassengers: "75M",
      terminals: "9 terminals",
      onTimePercentage: 74,
      averageSecurityMinutes: 24,
    },
    summary:
      "LAX has better food and lounges than its reputation suggests, but curbside logistics and terminal construction still punish unplanned arrivals.",
    bestFor: ["Transpacific flights", "Premium lounges", "Airside terminal connectors"],
    watchOutFor: ["Rideshare friction", "Construction detours", "Peak evening security"],
    amenities: [
      {
        id: "lax-food",
        label: "Best-in-class food pockets",
        category: "food",
        description: "TBIT and several renovated terminals have strong local options.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "lax-lounge",
        label: "Premium lounge depth",
        category: "lounge",
        description: "Flagship and alliance lounges are strongest around TBIT.",
        quality: "excellent",
      },
      {
        id: "lax-family",
        label: "Family rooms",
        category: "family",
        description: "Nursing and family facilities exist, but spacing depends on terminal.",
        quality: "good",
      },
      {
        id: "lax-access",
        label: "Improving accessibility",
        category: "accessibility",
        description: "Renovations have improved paths, elevators, and accessible restrooms.",
        quality: "good",
      },
      {
        id: "lax-transport",
        label: "FlyAway bus",
        category: "transport",
        description: "A practical low-stress option to Union Station or Van Nuys.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "lax-it",
        category: "transport",
        title: "Price the FlyAway before rideshare",
        summary: "The bus is often the calmer choice after long-haul arrivals.",
        details:
          "During surge windows, FlyAway to Union Station can be cheaper and emotionally easier than navigating LAX-it.",
        pro: "Predictable and luggage-friendly.",
        con: "Less useful if your final destination is far from a stop.",
      },
      {
        id: "lax-tbit",
        category: "food",
        title: "Use TBIT as your food and lounge anchor",
        summary: "Many of the best airside options cluster around Tom Bradley.",
        details:
          "If your terminal is connected airside, build in time to eat or lounge around TBIT before walking back.",
      },
      {
        id: "lax-short-walk",
        category: "navigation",
        title: "Walking can beat the shuttle",
        summary: "Adjacent terminals are often faster on foot.",
        details:
          "For light bags, walking one or two terminals can save time versus waiting at crowded curbside stops.",
      },
      {
        id: "lax-evening",
        category: "security",
        title: "Evening long-haul banks need padding",
        summary: "Security, bag drop, and curb traffic peak together.",
        details:
          "Add time for late afternoon and evening departures, especially around holidays and Pacific departures.",
      },
    ],
    transport: [
      {
        type: "bus",
        name: "FlyAway",
        summary: "Direct coach service to major LA nodes.",
        timeToCity: "35-60 min",
        cost: "$",
        insiderTip: "Union Station is the best transfer point for car-free onward travel.",
      },
      {
        type: "rideshare",
        name: "LAX-it pickup",
        summary: "Official rideshare and taxi pickup area.",
        timeToCity: "35-90 min",
        cost: "$$",
        insiderTip: "If your party is mobile, compare taxi wait times before opening the rideshare app.",
      },
      {
        type: "parking",
        name: "Economy parking",
        summary: "Better value than central terminal garages.",
        timeToCity: "On airport",
        cost: "$$",
        insiderTip: "Reserve in advance for early morning flights.",
      },
    ],
    disruption: {
      status: "minor",
      departureDelayMinutes: 18,
      departureDelayPercent: 17,
      arrivalDelayMinutes: 21,
      arrivalDelayPercent: 19,
      cancellationsPercent: 0.8,
      alerts: ["Marine layer visibility"],
      lastUpdated: new Date("2026-05-31T08:45:00Z"),
    },
    reviews: [
      {
        id: "lax-review-1",
        author: "Chris T.",
        tripType: "International connection",
        rating: 4,
        title: "Better inside than outside",
        body: "The airside experience was good. Getting picked up was the only painful part.",
        date: "2026-05-02",
      },
      {
        id: "lax-review-2",
        author: "Priya S.",
        tripType: "Weekend trip",
        rating: 3,
        title: "Give yourself curb time",
        body: "Food was excellent, but traffic around departures was worse than expected.",
        date: "2026-02-27",
      },
    ],
    photos: [
      { id: "lax-photo-1", alt: "Tom Bradley terminal", colorClass: "from-orange-200 to-slate-700" },
      { id: "lax-photo-2", alt: "Palm-lined approach", colorClass: "from-amber-200 to-cyan-700" },
      { id: "lax-photo-3", alt: "Renovated gate area", colorClass: "from-stone-200 to-zinc-700" },
    ],
  },
  {
    slug: "ord",
    iata: "ORD",
    icao: "KORD",
    name: "Chicago O'Hare International Airport",
    shortName: "Chicago O'Hare",
    city: "Chicago",
    country: "United States",
    region: "North America",
    coordinates: { latitude: 41.9742, longitude: -87.9073 },
    airportistScore: 7.1,
    scoreBreakdown: {
      comfort: 6.9,
      navigation: 7.0,
      food: 7.2,
      transport: 7.6,
      disruptionResilience: 6.6,
    },
    stats: {
      annualPassengers: "74M",
      terminals: "4 terminals",
      onTimePercentage: 71,
      averageSecurityMinutes: 21,
    },
    summary:
      "O'Hare is efficient for experienced travelers and nerve-racking during weather days. The CTA Blue Line is the stress-reducer most visitors underuse.",
    bestFor: ["Domestic connections", "CTA access", "United and American networks"],
    watchOutFor: ["Winter weather", "Long terminal walks", "Tight connection banks"],
    amenities: [
      {
        id: "ord-food",
        label: "Chicago food staples",
        category: "food",
        description: "Good casual food, especially if you avoid the most central concourses.",
        quality: "good",
      },
      {
        id: "ord-wifi",
        label: "Reliable WiFi",
        category: "wifi",
        description: "Free WiFi is generally stable for work sessions.",
        quality: "good",
      },
      {
        id: "ord-transport",
        label: "CTA Blue Line",
        category: "transport",
        description: "Direct rail to the Loop without traffic surprises.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "ord-lounge",
        label: "Hub lounges",
        category: "lounge",
        description: "Useful airline lounges, though crowding varies by bank.",
        quality: "good",
      },
      {
        id: "ord-access",
        label: "Accessible terminal paths",
        category: "accessibility",
        description: "Most paths are straightforward, but distances can be long.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "ord-blue-line",
        category: "transport",
        title: "Use the Blue Line if downtown traffic is red",
        summary: "It is not fancy, but it is dependable.",
        details:
          "For Loop hotels, CTA can beat rideshare during rush hour and major event traffic.",
      },
      {
        id: "ord-weather",
        category: "layover",
        title: "Build weather slack into winter connections",
        summary: "Small delays can cascade across banked hub schedules.",
        details:
          "If you can choose, avoid the last connection of the day during heavy snow or thunderstorm forecasts.",
        pro: "Earlier flights have more recovery options.",
      },
      {
        id: "ord-tunnel",
        category: "navigation",
        title: "Do not underestimate terminal walking time",
        summary: "The airport is logical but large.",
        details:
          "Check gate letters before grabbing food; a concourse change can turn a comfortable layover tight.",
      },
      {
        id: "ord-precheck",
        category: "security",
        title: "PreCheck matters most on Monday mornings",
        summary: "Business travel peaks can make standard security uneven.",
        details:
          "If you do not have PreCheck, arrive early on Monday and Thursday hub departure banks.",
      },
    ],
    transport: [
      {
        type: "metro",
        name: "CTA Blue Line",
        summary: "Direct rail link to downtown Chicago.",
        timeToCity: "40-50 min",
        cost: "$",
        insiderTip: "Use it when expressway traffic is already building.",
      },
      {
        type: "taxi",
        name: "Taxi stand",
        summary: "Reliable for central hotels outside peak congestion.",
        timeToCity: "35-75 min",
        cost: "$$",
        insiderTip: "Ask for estimated toll-inclusive fare before leaving the curb.",
      },
      {
        type: "parking",
        name: "Economy lots",
        summary: "Good for longer trips if you budget shuttle time.",
        timeToCity: "On airport",
        cost: "$",
        insiderTip: "Photograph your lot and shuttle stop before departure.",
      },
    ],
    disruption: {
      status: "moderate",
      departureDelayMinutes: 42,
      departureDelayPercent: 34,
      arrivalDelayMinutes: 36,
      arrivalDelayPercent: 29,
      cancellationsPercent: 1.7,
      alerts: ["Thunderstorms west of Chicago", "Hub connection congestion"],
      lastUpdated: new Date("2026-05-31T08:30:00Z"),
    },
    reviews: [
      {
        id: "ord-review-1",
        author: "Elena W.",
        tripType: "Domestic connection",
        rating: 4,
        title: "Efficient but huge",
        body: "My connection worked because I checked the concourse map before landing.",
        date: "2026-04-04",
      },
      {
        id: "ord-review-2",
        author: "Sam G.",
        tripType: "Business",
        rating: 3,
        title: "Weather risk is real",
        body: "Great network, but storms turned a short hop into a long evening.",
        date: "2026-01-22",
      },
    ],
    photos: [
      { id: "ord-photo-1", alt: "Terminal tunnel lights", colorClass: "from-indigo-200 to-blue-900" },
      { id: "ord-photo-2", alt: "Concourse gates", colorClass: "from-slate-200 to-zinc-800" },
      { id: "ord-photo-3", alt: "Train platform", colorClass: "from-sky-200 to-cyan-900" },
    ],
  },
  {
    slug: "atl",
    iata: "ATL",
    icao: "KATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    shortName: "Atlanta ATL",
    city: "Atlanta",
    country: "United States",
    region: "North America",
    coordinates: { latitude: 33.6407, longitude: -84.4277 },
    airportistScore: 8.1,
    scoreBreakdown: {
      comfort: 7.5,
      navigation: 8.8,
      food: 7.6,
      transport: 8.2,
      disruptionResilience: 8.4,
    },
    stats: {
      annualPassengers: "104M",
      terminals: "2 terminals, 7 concourses",
      onTimePercentage: 79,
      averageSecurityMinutes: 19,
    },
    summary:
      "ATL is massive but unusually logical. The Plane Train and parallel concourses make it one of the least confusing mega-hubs.",
    bestFor: ["Fast domestic connections", "MARTA access", "Predictable layout"],
    watchOutFor: ["South security crowding", "Long walks if train pauses", "Dense Delta banks"],
    amenities: [
      {
        id: "atl-transport",
        label: "MARTA rail",
        category: "transport",
        description: "Direct rail to central Atlanta from the domestic terminal.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "atl-food",
        label: "Southern food options",
        category: "food",
        description: "Good regional choices across several concourses.",
        quality: "good",
      },
      {
        id: "atl-wifi",
        label: "Fast WiFi",
        category: "wifi",
        description: "Reliable enough for calls and work between flights.",
        quality: "good",
      },
      {
        id: "atl-family",
        label: "Family friendly",
        category: "family",
        description: "Clear layout, frequent trains, and many restrooms help families.",
        quality: "excellent",
      },
      {
        id: "atl-lounge",
        label: "Delta lounge network",
        category: "lounge",
        description: "Sky Clubs are convenient but often crowded during peak banks.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "atl-plane-train",
        category: "navigation",
        title: "Learn the Plane Train pattern once",
        summary: "Concourses are ordered and easy to recover from.",
        details:
          "Every concourse connects by train and pedestrian tunnel. If you miss a stop, recovery is simple.",
        pro: "Excellent for tight domestic connections.",
      },
      {
        id: "atl-security",
        category: "security",
        title: "Check North versus South security",
        summary: "The less obvious checkpoint can save real time.",
        details:
          "Domestic terminal security loads vary. If one side is backed up, staff may direct eligible travelers to alternatives.",
      },
      {
        id: "atl-marta",
        category: "transport",
        title: "MARTA is the default for downtown",
        summary: "Skip highway uncertainty when going central.",
        details:
          "For Midtown or Downtown, MARTA is often the best balance of cost, speed, and predictability.",
      },
      {
        id: "atl-food",
        category: "food",
        title: "Do not settle at the first concourse",
        summary: "A one-stop train hop can improve food choices.",
        details:
          "If you have more than 50 minutes, check options in adjacent concourses before committing.",
      },
    ],
    transport: [
      {
        type: "metro",
        name: "MARTA",
        summary: "Direct rail from the domestic terminal.",
        timeToCity: "20-25 min",
        cost: "$",
        insiderTip: "Best for Downtown, Midtown, and connections to the rail network.",
      },
      {
        type: "rideshare",
        name: "Rideshare pickup",
        summary: "Straightforward but can slow during convention weeks.",
        timeToCity: "20-50 min",
        cost: "$$",
        insiderTip: "Use MARTA if traffic maps show red around I-85.",
      },
      {
        type: "parking",
        name: "Airport parking",
        summary: "Multiple on-airport options with frequent shuttles.",
        timeToCity: "On airport",
        cost: "$$",
        insiderTip: "Reserve remote parking early around holiday weekends.",
      },
    ],
    disruption: {
      status: "normal",
      departureDelayMinutes: 9,
      departureDelayPercent: 8,
      arrivalDelayMinutes: 7,
      arrivalDelayPercent: 6,
      cancellationsPercent: 0.3,
      alerts: [],
      lastUpdated: new Date("2026-05-31T08:55:00Z"),
    },
    reviews: [
      {
        id: "atl-review-1",
        author: "Nora P.",
        tripType: "Domestic connection",
        rating: 5,
        title: "Huge but easy",
        body: "The train makes ATL less stressful than many smaller airports.",
        date: "2026-05-13",
      },
      {
        id: "atl-review-2",
        author: "Diego M.",
        tripType: "Family visit",
        rating: 4,
        title: "MARTA wins",
        body: "Rail into town was cheaper and faster than the rideshare estimate.",
        date: "2026-03-16",
      },
    ],
    photos: [
      { id: "atl-photo-1", alt: "Plane Train escalators", colorClass: "from-red-200 to-zinc-800" },
      { id: "atl-photo-2", alt: "Wide concourse", colorClass: "from-amber-200 to-stone-700" },
      { id: "atl-photo-3", alt: "MARTA station", colorClass: "from-emerald-200 to-slate-800" },
    ],
  },
  {
    slug: "lhr",
    iata: "LHR",
    icao: "EGLL",
    name: "London Heathrow Airport",
    shortName: "London Heathrow",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    coordinates: { latitude: 51.47, longitude: -0.4543 },
    airportistScore: 7.8,
    scoreBreakdown: {
      comfort: 7.7,
      navigation: 7.4,
      food: 8.0,
      transport: 8.8,
      disruptionResilience: 7.1,
    },
    stats: {
      annualPassengers: "79M",
      terminals: "4 terminals",
      onTimePercentage: 72,
      averageSecurityMinutes: 20,
    },
    summary:
      "Heathrow is polished and exceptionally connected to London, but terminal separation and border waves make planning essential.",
    bestFor: ["Rail into London", "Premium lounges", "Global long-haul network"],
    watchOutFor: ["Border queues", "Terminal transfers", "Slot-related delays"],
    amenities: [
      {
        id: "lhr-transport",
        label: "Elite rail access",
        category: "transport",
        description: "Elizabeth line, Heathrow Express, and Tube offer multiple price-speed choices.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "lhr-lounge",
        label: "World-class lounges",
        category: "lounge",
        description: "Terminal 3 and Terminal 5 are especially strong for premium travelers.",
        quality: "excellent",
      },
      {
        id: "lhr-shopping",
        label: "High-end shopping",
        category: "shopping",
        description: "Luxury retail is abundant, especially in flagship terminals.",
        quality: "excellent",
      },
      {
        id: "lhr-access",
        label: "Accessible services",
        category: "accessibility",
        description: "Strong assistance program, but request support ahead for transfers.",
        quality: "good",
      },
      {
        id: "lhr-food",
        label: "Reliable dining",
        category: "food",
        description: "Good sit-down and quick-service choices after security.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "lhr-rail-choice",
        category: "transport",
        title: "Match rail to your exact London destination",
        summary: "Fastest and best value are not always the same line.",
        details:
          "Heathrow Express is fast to Paddington; Elizabeth line is often better for the West End, City, or Canary Wharf.",
        pro: "You can avoid road traffic completely.",
      },
      {
        id: "lhr-terminal",
        category: "navigation",
        title: "Treat terminal transfers as serious time",
        summary: "Terminals are not casual walking distance.",
        details:
          "If your itinerary changes terminals, check the official transfer route and minimum connection time before booking.",
      },
      {
        id: "lhr-border",
        category: "security",
        title: "Border waves define arrival stress",
        summary: "Several widebody arrivals can change the whole mood.",
        details:
          "Eligible eGates help a lot. Families and visa checks should plan more buffer.",
      },
      {
        id: "lhr-t5",
        category: "lounge",
        title: "Terminal 5 rewards early lounge planning",
        summary: "North and South lounge crowding can differ sharply.",
        details:
          "Check which lounge is closest to your gate area and be ready to switch if one is full.",
      },
    ],
    transport: [
      {
        type: "train",
        name: "Elizabeth line",
        summary: "Best balance of reach and price for many London trips.",
        timeToCity: "35-55 min",
        cost: "$$",
        insiderTip: "Often better than Heathrow Express if you are not staying near Paddington.",
      },
      {
        type: "train",
        name: "Heathrow Express",
        summary: "Fast premium rail to Paddington.",
        timeToCity: "15 min",
        cost: "$$$",
        insiderTip: "Book ahead if you know you want speed over price.",
      },
      {
        type: "taxi",
        name: "Black cab or car service",
        summary: "Useful with heavy bags or late arrivals.",
        timeToCity: "45-90 min",
        cost: "$$$",
        insiderTip: "Road travel can be slow into central London at peak times.",
      },
    ],
    disruption: {
      status: "minor",
      departureDelayMinutes: 16,
      departureDelayPercent: 14,
      arrivalDelayMinutes: 25,
      arrivalDelayPercent: 20,
      cancellationsPercent: 0.9,
      alerts: ["Arrival flow controls"],
      lastUpdated: new Date("2026-05-31T08:50:00Z"),
    },
    reviews: [
      {
        id: "lhr-review-1",
        author: "Amelia B.",
        tripType: "Long-haul business",
        rating: 4,
        title: "Polished but busy",
        body: "Great rail and lounge options. Border queue was the only drag.",
        date: "2026-04-21",
      },
      {
        id: "lhr-review-2",
        author: "Kenji A.",
        tripType: "Family holiday",
        rating: 4,
        title: "Elizabeth line changed everything",
        body: "Getting to our hotel was simpler than expected once we skipped the car.",
        date: "2026-02-08",
      },
    ],
    photos: [
      { id: "lhr-photo-1", alt: "Terminal 5 departures", colorClass: "from-violet-200 to-slate-800" },
      { id: "lhr-photo-2", alt: "Elizabeth line station", colorClass: "from-purple-200 to-indigo-900" },
      { id: "lhr-photo-3", alt: "Premium lounge", colorClass: "from-amber-100 to-stone-800" },
    ],
  },
  {
    slug: "cdg",
    iata: "CDG",
    icao: "LFPG",
    name: "Paris Charles de Gaulle Airport",
    shortName: "Paris CDG",
    city: "Paris",
    country: "France",
    region: "Europe",
    coordinates: { latitude: 49.0097, longitude: 2.5479 },
    airportistScore: 6.8,
    scoreBreakdown: {
      comfort: 7.0,
      navigation: 5.9,
      food: 7.4,
      transport: 7.5,
      disruptionResilience: 6.2,
    },
    stats: {
      annualPassengers: "67M",
      terminals: "3 terminals",
      onTimePercentage: 69,
      averageSecurityMinutes: 26,
    },
    summary:
      "CDG has style and solid rail access, but signage, terminal geometry, and bus transfers can make it feel harder than it should.",
    bestFor: ["Paris rail access", "Luxury shopping", "Air France network"],
    watchOutFor: ["Terminal 2 complexity", "Remote stands", "Strike-related disruption"],
    amenities: [
      {
        id: "cdg-food",
        label: "French dining pockets",
        category: "food",
        description: "Better than average cafes and bakeries, strongest in renovated areas.",
        quality: "good",
      },
      {
        id: "cdg-shopping",
        label: "Luxury retail",
        category: "shopping",
        description: "Strong fashion, beauty, and duty-free selection.",
        quality: "excellent",
      },
      {
        id: "cdg-transport",
        label: "RER B and TGV",
        category: "transport",
        description: "Rail is useful both into Paris and to French regions.",
        quality: "good",
        isFeatured: true,
      },
      {
        id: "cdg-family",
        label: "Family services",
        category: "family",
        description: "Play areas exist but can be hard to find on tight connections.",
        quality: "basic",
      },
      {
        id: "cdg-lounge",
        label: "Air France lounges",
        category: "lounge",
        description: "Strong premium spaces in key long-haul zones.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "cdg-2e",
        category: "navigation",
        title: "Know your exact 2E hall",
        summary: "Terminal 2E is not one simple building.",
        details:
          "Hall K, L, and M transfers can involve trains or longer walks. Gate hall matters more than terminal number.",
        con: "A vague terminal note is not enough for tight connections.",
      },
      {
        id: "cdg-rer",
        category: "transport",
        title: "RER B is efficient but watch disruptions",
        summary: "Great value when running normally.",
        details:
          "Check service status before committing. If there are works or strikes, compare fixed-price taxis.",
      },
      {
        id: "cdg-food",
        category: "food",
        title: "Eat after security in renovated halls",
        summary: "Quality varies sharply by terminal zone.",
        details:
          "If you see a strong bakery or cafe in your gate hall, do not assume the next zone will be better.",
      },
      {
        id: "cdg-buffer",
        category: "layover",
        title: "Do not book heroic self-transfers",
        summary: "CDG rewards conservative connection planning.",
        details:
          "Passport control, remote stands, and terminal buses can combine into an unexpectedly long transfer.",
      },
    ],
    transport: [
      {
        type: "train",
        name: "RER B",
        summary: "Budget rail into central Paris.",
        timeToCity: "35-50 min",
        cost: "$",
        insiderTip: "Check for works or strikes before buying a ticket.",
      },
      {
        type: "train",
        name: "TGV station",
        summary: "Useful for onward French and Belgian cities.",
        timeToCity: "On airport",
        cost: "$$",
        insiderTip: "Leave time to reach the station from your terminal.",
      },
      {
        type: "taxi",
        name: "Official taxi",
        summary: "Fixed fares to Paris zones.",
        timeToCity: "35-80 min",
        cost: "$$",
        insiderTip: "Use official ranks only and confirm the fixed fare zone.",
      },
    ],
    disruption: {
      status: "moderate",
      departureDelayMinutes: 35,
      departureDelayPercent: 28,
      arrivalDelayMinutes: 32,
      arrivalDelayPercent: 25,
      cancellationsPercent: 2.8,
      alerts: ["ATC staffing", "Rail service works"],
      lastUpdated: new Date("2026-05-31T08:20:00Z"),
    },
    reviews: [
      {
        id: "cdg-review-1",
        author: "Lucia F.",
        tripType: "Europe connection",
        rating: 3,
        title: "Beautiful but confusing",
        body: "The lounge was lovely. Finding the right hall took more effort than expected.",
        date: "2026-04-02",
      },
      {
        id: "cdg-review-2",
        author: "Theo C.",
        tripType: "City break",
        rating: 4,
        title: "RER was easy",
        body: "Rail into Paris was simple once we followed signs to the station.",
        date: "2026-03-18",
      },
    ],
    photos: [
      { id: "cdg-photo-1", alt: "Curved terminal architecture", colorClass: "from-rose-100 to-slate-800" },
      { id: "cdg-photo-2", alt: "Luxury retail corridor", colorClass: "from-yellow-100 to-stone-900" },
      { id: "cdg-photo-3", alt: "Rail station signs", colorClass: "from-blue-100 to-indigo-800" },
    ],
  },
  {
    slug: "fra",
    iata: "FRA",
    icao: "EDDF",
    name: "Frankfurt Airport",
    shortName: "Frankfurt FRA",
    city: "Frankfurt",
    country: "Germany",
    region: "Europe",
    coordinates: { latitude: 50.0379, longitude: 8.5622 },
    airportistScore: 7.5,
    scoreBreakdown: {
      comfort: 7.1,
      navigation: 7.2,
      food: 7.0,
      transport: 9.0,
      disruptionResilience: 7.3,
    },
    stats: {
      annualPassengers: "59M",
      terminals: "2 terminals",
      onTimePercentage: 75,
      averageSecurityMinutes: 18,
    },
    summary:
      "FRA is a serious connection machine with superb rail integration. It feels utilitarian, but frequent travelers appreciate the predictability.",
    bestFor: ["Rail connections", "Lufthansa network", "Business travel"],
    watchOutFor: ["Long walking distances", "Schengen checks", "Bus gates"],
    amenities: [
      {
        id: "fra-transport",
        label: "Long-distance rail station",
        category: "transport",
        description: "One of the best airport rail stations in the world.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "fra-lounge",
        label: "Lufthansa lounges",
        category: "lounge",
        description: "Strong but sometimes crowded hub lounge network.",
        quality: "good",
      },
      {
        id: "fra-wifi",
        label: "Reliable WiFi",
        category: "wifi",
        description: "Good connectivity for working travelers.",
        quality: "good",
      },
      {
        id: "fra-shopping",
        label: "Practical shopping",
        category: "shopping",
        description: "Good essentials, pharmacies, and duty-free options.",
        quality: "good",
      },
      {
        id: "fra-access",
        label: "Accessible routing",
        category: "accessibility",
        description: "Strong assistance options, but request help early for long connections.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "fra-rail",
        category: "transport",
        title: "Use FRA as a rail-air hub",
        summary: "The train station can replace a short connecting flight.",
        details:
          "For Cologne, Stuttgart, and other German cities, ICE rail can be less stressful than another flight.",
        pro: "Excellent onward rail network.",
      },
      {
        id: "fra-walk",
        category: "navigation",
        title: "Respect the walking distances",
        summary: "Connections can be longer than the map suggests.",
        details:
          "Passport checks, security rechecks, and bus gates can make a 60-minute connection feel tight.",
      },
      {
        id: "fra-food",
        category: "food",
        title: "Eat before remote gates",
        summary: "Food choices thin out near some bus departures.",
        details:
          "If your gate is remote or in a sparse pier, buy snacks before committing to the final gate area.",
      },
      {
        id: "fra-security",
        category: "security",
        title: "Keep liquids and electronics tidy",
        summary: "Screening can be precise and slow when bags are messy.",
        details:
          "A well-packed carry-on pays off at FRA more than at many airports.",
      },
    ],
    transport: [
      {
        type: "train",
        name: "ICE long-distance rail",
        summary: "High-speed rail to German and regional cities.",
        timeToCity: "10-15 min to Frankfurt",
        cost: "$$",
        insiderTip: "Check whether your airline ticket includes Rail&Fly.",
      },
      {
        type: "metro",
        name: "S-Bahn",
        summary: "Fast link to Frankfurt city center.",
        timeToCity: "15 min",
        cost: "$",
        insiderTip: "Best for central hotels and the main station.",
      },
      {
        type: "taxi",
        name: "Taxi",
        summary: "Easy for late arrivals or suburbs.",
        timeToCity: "20-35 min",
        cost: "$$",
        insiderTip: "Rail is usually faster to the city center during peak times.",
      },
    ],
    disruption: {
      status: "normal",
      departureDelayMinutes: 12,
      departureDelayPercent: 11,
      arrivalDelayMinutes: 13,
      arrivalDelayPercent: 12,
      cancellationsPercent: 0.5,
      alerts: [],
      lastUpdated: new Date("2026-05-31T08:35:00Z"),
    },
    reviews: [
      {
        id: "fra-review-1",
        author: "Martin H.",
        tripType: "Rail connection",
        rating: 5,
        title: "Train integration is unbeatable",
        body: "I landed and was on an ICE within an hour. Very efficient.",
        date: "2026-05-06",
      },
      {
        id: "fra-review-2",
        author: "Sofia L.",
        tripType: "Schengen connection",
        rating: 3,
        title: "Long walks",
        body: "Everything worked, but my connection involved more walking than expected.",
        date: "2026-02-14",
      },
    ],
    photos: [
      { id: "fra-photo-1", alt: "Rail station atrium", colorClass: "from-emerald-100 to-zinc-800" },
      { id: "fra-photo-2", alt: "Terminal hall", colorClass: "from-slate-100 to-neutral-800" },
      { id: "fra-photo-3", alt: "Gate corridor", colorClass: "from-cyan-100 to-slate-900" },
    ],
  },
  {
    slug: "dxb",
    iata: "DXB",
    icao: "OMDB",
    name: "Dubai International Airport",
    shortName: "Dubai DXB",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    coordinates: { latitude: 25.2532, longitude: 55.3657 },
    airportistScore: 8.0,
    scoreBreakdown: {
      comfort: 8.2,
      navigation: 7.5,
      food: 8.0,
      transport: 7.8,
      disruptionResilience: 8.3,
    },
    stats: {
      annualPassengers: "87M",
      terminals: "3 terminals",
      onTimePercentage: 78,
      averageSecurityMinutes: 17,
    },
    summary:
      "DXB is built for 24-hour long-haul movement: polished, busy, lounge-heavy, and surprisingly manageable if you plan sleep and gate distance.",
    bestFor: ["Long-haul connections", "Late-night services", "Lounges and shopping"],
    watchOutFor: ["Huge concourses", "Overnight crowding", "Long bus gates"],
    amenities: [
      {
        id: "dxb-shopping",
        label: "24-hour shopping",
        category: "shopping",
        description: "Huge retail footprint with late-night energy.",
        quality: "excellent",
      },
      {
        id: "dxb-lounge",
        label: "Excellent lounges",
        category: "lounge",
        description: "Premium and paid lounge options are among the world's strongest.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "dxb-sleep",
        label: "Sleep options",
        category: "sleep",
        description: "Transit hotels and sleep pods help long connections.",
        quality: "good",
      },
      {
        id: "dxb-food",
        label: "Round-the-clock food",
        category: "food",
        description: "Food options remain open deeper into the night than most hubs.",
        quality: "good",
      },
      {
        id: "dxb-wifi",
        label: "Fast WiFi",
        category: "wifi",
        description: "Reliable WiFi across most passenger areas.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "dxb-gate-distance",
        category: "navigation",
        title: "Check gate distance before relaxing",
        summary: "Some DXB walks are much longer than they look.",
        details:
          "Do your food, lounge, or shopping plan after confirming the gate pier and boarding time.",
      },
      {
        id: "dxb-sleep",
        category: "layover",
        title: "Book sleep proactively on overnight layovers",
        summary: "The airport is alive all night, not quiet all night.",
        details:
          "If you need real rest, reserve a transit hotel or sleep pod instead of hoping for empty benches.",
        pro: "Very strong paid rest options.",
        con: "Walk-up availability can disappear during bank peaks.",
      },
      {
        id: "dxb-metro",
        category: "transport",
        title: "Use Metro for predictable city trips",
        summary: "It is clean, cheap, and avoids road surprises.",
        details:
          "Metro is excellent for many Dubai destinations, though taxis still win for beach resorts with luggage.",
      },
      {
        id: "dxb-food",
        category: "food",
        title: "Eat away from the busiest Emirates banks",
        summary: "A short walk can mean shorter lines.",
        details:
          "During late-night connection waves, restaurants near central nodes fill first.",
      },
    ],
    transport: [
      {
        type: "metro",
        name: "Dubai Metro",
        summary: "Clean rail link to many central areas.",
        timeToCity: "20-35 min",
        cost: "$",
        insiderTip: "Check operating hours for very late arrivals.",
      },
      {
        type: "taxi",
        name: "Official taxi",
        summary: "Easy and well organized at arrivals.",
        timeToCity: "15-35 min",
        cost: "$$",
        insiderTip: "Best for hotels away from Metro stations.",
      },
      {
        type: "parking",
        name: "Short-term parking",
        summary: "Convenient for pickups and short visits.",
        timeToCity: "On airport",
        cost: "$$",
        insiderTip: "Terminal choice matters because inter-terminal movement takes time.",
      },
    ],
    disruption: {
      status: "normal",
      departureDelayMinutes: 10,
      departureDelayPercent: 9,
      arrivalDelayMinutes: 11,
      arrivalDelayPercent: 10,
      cancellationsPercent: 0.2,
      alerts: [],
      lastUpdated: new Date("2026-05-31T08:48:00Z"),
    },
    reviews: [
      {
        id: "dxb-review-1",
        author: "Hassan N.",
        tripType: "Overnight connection",
        rating: 5,
        title: "Made for layovers",
        body: "I booked a sleep pod and the connection felt almost easy.",
        date: "2026-04-29",
      },
      {
        id: "dxb-review-2",
        author: "Claire D.",
        tripType: "Long-haul",
        rating: 4,
        title: "Huge but smooth",
        body: "Everything was open late, but my gate was a serious walk.",
        date: "2026-03-11",
      },
    ],
    photos: [
      { id: "dxb-photo-1", alt: "Late-night concourse", colorClass: "from-yellow-100 to-slate-900" },
      { id: "dxb-photo-2", alt: "Retail atrium", colorClass: "from-amber-200 to-stone-900" },
      { id: "dxb-photo-3", alt: "Metro signs", colorClass: "from-cyan-100 to-blue-900" },
    ],
  },
  {
    slug: "sin",
    iata: "SIN",
    icao: "WSSS",
    name: "Singapore Changi Airport",
    shortName: "Singapore Changi",
    city: "Singapore",
    country: "Singapore",
    region: "Asia-Pacific",
    coordinates: { latitude: 1.3644, longitude: 103.9915 },
    airportistScore: 9.3,
    scoreBreakdown: {
      comfort: 9.6,
      navigation: 9.2,
      food: 9.0,
      transport: 8.8,
      disruptionResilience: 9.1,
    },
    stats: {
      annualPassengers: "59M",
      terminals: "4 terminals",
      onTimePercentage: 84,
      averageSecurityMinutes: 11,
    },
    summary:
      "Changi is the rare airport worth arriving early for. It combines calm operations, excellent amenities, and practical transit comfort.",
    bestFor: ["Long layovers", "Families", "Food and gardens"],
    watchOutFor: ["Jewel timing", "Terminal-specific security", "Late-night transport gaps"],
    amenities: [
      {
        id: "sin-family",
        label: "Exceptional family facilities",
        category: "family",
        description: "Play areas, gardens, and calm spaces make family waits easier.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "sin-food",
        label: "Excellent food",
        category: "food",
        description: "Strong hawker-style and international choices across terminals and Jewel.",
        quality: "excellent",
      },
      {
        id: "sin-sleep",
        label: "Rest and transit hotels",
        category: "sleep",
        description: "Transit hotels, nap areas, and quiet zones are genuinely useful.",
        quality: "excellent",
      },
      {
        id: "sin-wifi",
        label: "Fast WiFi",
        category: "wifi",
        description: "Stable free WiFi supports work and video calls.",
        quality: "excellent",
      },
      {
        id: "sin-access",
        label: "Accessible and calm",
        category: "accessibility",
        description: "Clear design and staff support make the airport easy to navigate.",
        quality: "excellent",
      },
    ],
    tips: [
      {
        id: "sin-jewel",
        category: "layover",
        title: "Only visit Jewel if immigration timing works",
        summary: "Jewel is landside, not a simple gate detour.",
        details:
          "For long layovers it is worth it, but check immigration, bag, and re-entry timing before leaving airside.",
        pro: "One of the world's best airport attractions.",
        con: "Not always safe for short international connections.",
      },
      {
        id: "sin-security",
        category: "security",
        title: "Remember security is often at the gate",
        summary: "Do not wait too long to enter the gate hold room.",
        details:
          "Some flights screen near the gate, so boarding areas can close earlier than travelers expect.",
      },
      {
        id: "sin-food",
        category: "food",
        title: "Plan meals around terminal strengths",
        summary: "Food is good almost everywhere, but Jewel expands choices.",
        details:
          "If landside time is available, Jewel adds many more options than most airside zones.",
      },
      {
        id: "sin-rest",
        category: "layover",
        title: "Use Changi for real recovery",
        summary: "This is one airport where a long layover can be productive.",
        details:
          "Showers, transit hotels, quiet corners, and gardens make six hours feel manageable.",
      },
    ],
    transport: [
      {
        type: "metro",
        name: "MRT",
        summary: "Clean rail into the city with one transfer.",
        timeToCity: "35-45 min",
        cost: "$",
        insiderTip: "Best during daytime and early evening arrivals.",
      },
      {
        type: "taxi",
        name: "Taxi",
        summary: "Organized and reliable for hotels.",
        timeToCity: "20-35 min",
        cost: "$$",
        insiderTip: "Late-night surcharges can apply.",
      },
      {
        type: "bus",
        name: "Airport bus",
        summary: "Budget option for light travelers.",
        timeToCity: "45-70 min",
        cost: "$",
        insiderTip: "MRT is usually simpler unless your destination is bus-convenient.",
      },
    ],
    disruption: {
      status: "normal",
      departureDelayMinutes: 6,
      departureDelayPercent: 5,
      arrivalDelayMinutes: 8,
      arrivalDelayPercent: 7,
      cancellationsPercent: 0.1,
      alerts: [],
      lastUpdated: new Date("2026-05-31T08:58:00Z"),
    },
    reviews: [
      {
        id: "sin-review-1",
        author: "Rachel Y.",
        tripType: "Long layover",
        rating: 5,
        title: "The benchmark",
        body: "I arrived tired and left rested. That almost never happens in an airport.",
        date: "2026-05-20",
      },
      {
        id: "sin-review-2",
        author: "Omar A.",
        tripType: "Family connection",
        rating: 5,
        title: "Family travel made easier",
        body: "The kids had space to reset before the next long flight.",
        date: "2026-03-26",
      },
    ],
    photos: [
      { id: "sin-photo-1", alt: "Indoor garden", colorClass: "from-emerald-100 to-teal-900" },
      { id: "sin-photo-2", alt: "Jewel waterfall", colorClass: "from-cyan-100 to-emerald-900" },
      { id: "sin-photo-3", alt: "Quiet seating", colorClass: "from-lime-100 to-slate-800" },
    ],
  },
  {
    slug: "hnd",
    iata: "HND",
    icao: "RJTT",
    name: "Tokyo Haneda Airport",
    shortName: "Tokyo Haneda",
    city: "Tokyo",
    country: "Japan",
    region: "Asia-Pacific",
    coordinates: { latitude: 35.5494, longitude: 139.7798 },
    airportistScore: 8.7,
    scoreBreakdown: {
      comfort: 8.6,
      navigation: 8.9,
      food: 8.4,
      transport: 9.2,
      disruptionResilience: 8.2,
    },
    stats: {
      annualPassengers: "79M",
      terminals: "3 terminals",
      onTimePercentage: 83,
      averageSecurityMinutes: 13,
    },
    summary:
      "Haneda is close to Tokyo, clean, and precise. It is one of the easiest major airports for first-time visitors to Japan.",
    bestFor: ["Tokyo access", "Clean facilities", "Efficient domestic links"],
    watchOutFor: ["Last-train timing", "Terminal differences", "Typhoon season"],
    amenities: [
      {
        id: "hnd-transport",
        label: "Excellent city access",
        category: "transport",
        description: "Monorail and Keikyu make central Tokyo unusually easy.",
        quality: "excellent",
        isFeatured: true,
      },
      {
        id: "hnd-food",
        label: "Great Japanese dining",
        category: "food",
        description: "Good ramen, sushi, cafes, and convenience food options.",
        quality: "excellent",
      },
      {
        id: "hnd-family",
        label: "Family friendly",
        category: "family",
        description: "Clean restrooms, calm spaces, and clear signage help families.",
        quality: "excellent",
      },
      {
        id: "hnd-access",
        label: "High accessibility",
        category: "accessibility",
        description: "Elevators, signage, and staff support are strong.",
        quality: "excellent",
      },
      {
        id: "hnd-shopping",
        label: "Souvenir shopping",
        category: "shopping",
        description: "Excellent last-minute gifts and Japanese snacks.",
        quality: "good",
      },
    ],
    tips: [
      {
        id: "hnd-train",
        category: "transport",
        title: "Check the last train before late arrivals",
        summary: "Haneda is close, but rail is not 24-hour.",
        details:
          "For late-night arrivals, compare train timing with taxi cost before leaving baggage claim.",
      },
      {
        id: "hnd-food",
        category: "food",
        title: "Eat before security if you want variety",
        summary: "Landside dining can be more interesting than gate-side options.",
        details:
          "If you have time, the public areas offer strong Japanese food and souvenir choices.",
      },
      {
        id: "hnd-domestic",
        category: "navigation",
        title: "Domestic connections are highly efficient",
        summary: "But terminal choice still matters.",
        details:
          "Check airline terminal assignments carefully because domestic and international flows differ.",
      },
      {
        id: "hnd-weather",
        category: "layover",
        title: "Watch typhoon season buffers",
        summary: "Operations are excellent until weather gets extreme.",
        details:
          "During typhoon alerts, pick earlier flights and monitor rail operations into Tokyo.",
      },
    ],
    transport: [
      {
        type: "train",
        name: "Tokyo Monorail",
        summary: "Fast link toward Hamamatsucho.",
        timeToCity: "15-25 min",
        cost: "$",
        insiderTip: "Good for JR connections on the Yamanote Line.",
      },
      {
        type: "train",
        name: "Keikyu Line",
        summary: "Useful for Shinagawa and through-running services.",
        timeToCity: "15-30 min",
        cost: "$",
        insiderTip: "Often best for hotels around Shinagawa or Yokohama.",
      },
      {
        type: "taxi",
        name: "Taxi",
        summary: "Practical late at night because Haneda is close to central Tokyo.",
        timeToCity: "25-45 min",
        cost: "$$$",
        insiderTip: "More reasonable than a Narita taxi, but still expensive.",
      },
    ],
    disruption: {
      status: "minor",
      departureDelayMinutes: 15,
      departureDelayPercent: 13,
      arrivalDelayMinutes: 18,
      arrivalDelayPercent: 15,
      cancellationsPercent: 0.6,
      alerts: ["Crosswind runway spacing"],
      lastUpdated: new Date("2026-05-31T08:42:00Z"),
    },
    reviews: [
      {
        id: "hnd-review-1",
        author: "Yuki T.",
        tripType: "Domestic connection",
        rating: 5,
        title: "Effortless",
        body: "Clean, clear, and close to town. My favorite big-city airport.",
        date: "2026-04-11",
      },
      {
        id: "hnd-review-2",
        author: "Ben L.",
        tripType: "First Japan trip",
        rating: 4,
        title: "Easy arrival",
        body: "The train signs made the city transfer very simple.",
        date: "2026-02-19",
      },
    ],
    photos: [
      { id: "hnd-photo-1", alt: "Observation deck", colorClass: "from-pink-100 to-slate-900" },
      { id: "hnd-photo-2", alt: "Train entrance", colorClass: "from-sky-100 to-blue-900" },
      { id: "hnd-photo-3", alt: "Japanese dining street", colorClass: "from-red-100 to-stone-900" },
    ],
  },
] satisfies Airport[];
